version: '3.8'
services:
    app:
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATA_REDIS_HOST: redis
      links:
        - redis
    redis:
      container_name: redis
      image: redis:latest
      command: ["redis-server"]
      healthcheck:
        test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
        interval: 1s
        timeout: 3s
        retries: 5
      ports:
        - "6379:6379"